name: Build hellow binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_x86_musl:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Building using Docker
      run: |
        cat Dockerfile
        docker build -t hellow .
        docker run --name hellow hellow
        docker cp hellow:/hellow/target/release/hellow .

    - name: Archive compilation target for ${{ matrix.os }}-${{ matrix.version }}
      uses: actions/upload-artifact@v4
      with:
        name: hellow
        if-no-files-found: ignore
        path: |
          hellow





